path:
    exp_data_dir: "mnist_results"
    logdir: 'mnist_runs'
    clean_data_dir: False
    data_path: "/app/data"
data:
    num_workers: 4
    shuffle: True
    test_batch_size: 1000
    mnist_mean: 0.1307
    mnist_std: 0.3081
train:
    epochs: 25
    log_interval: 10
    log_img_freq: 200
    gamma: 0.1
    n_sched: 3
